// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6NKGRmpRTgFthE9KdGB9sdav-BAe_smg',
    appId: '1:63543931753:web:1bda0177faee73760603f8',
    messagingSenderId: '63543931753',
    projectId: 'authentication-b9001',
    authDomain: 'authentication-b9001.firebaseapp.com',
    storageBucket: 'authentication-b9001.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsrdf5gdYFE7yEwc_3_BAPklEcr1hpbcs',
    appId: '1:63543931753:android:feef907c14697f5e0603f8',
    messagingSenderId: '63543931753',
    projectId: 'authentication-b9001',
    storageBucket: 'authentication-b9001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLjE3YKICYFDF_6JINbno3AYD6OJ9-RzU',
    appId: '1:63543931753:ios:b59f1777ac515a4d0603f8',
    messagingSenderId: '63543931753',
    projectId: 'authentication-b9001',
    storageBucket: 'authentication-b9001.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLjE3YKICYFDF_6JINbno3AYD6OJ9-RzU',
    appId: '1:63543931753:ios:b59f1777ac515a4d0603f8',
    messagingSenderId: '63543931753',
    projectId: 'authentication-b9001',
    storageBucket: 'authentication-b9001.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6NKGRmpRTgFthE9KdGB9sdav-BAe_smg',
    appId: '1:63543931753:web:39a39e6cbcedffec0603f8',
    messagingSenderId: '63543931753',
    projectId: 'authentication-b9001',
    authDomain: 'authentication-b9001.firebaseapp.com',
    storageBucket: 'authentication-b9001.appspot.com',
  );
}
